### PR TITLE
Add cookstyle and foodcritic

### PR DESCRIPTION
**Pull request by jeffbyrnes**

### CODE REVIEW

**Comment by thoutenbos** [comment]
@jeffbyrnes Sorry for merging out-of-order. Would you be able to rebase your branch ?

**Comment by jeffbyrnes** [comment]
Stand by on merging trying something out with Travis to see if it’s easier to grok as matrix or stages style build.

**Comment by jeffbyrnes** [comment]
@thoutenbos ok! I think this is all good now. Please review, and let me know if you feel anything is too opinionated or antagonistic to how you would like to maintain the cookbook.

There is one foodcritic failure I can’t really sort without doing some significant work, so I figured I’d leave that to someone more familiar with the cookbook.

**Comment by jeffbyrnes** [comment]
@thoutenbos by the way, the failing kitchen tests appear to be due to some SSL difficulties w/ Travis. I’ve seen this before. Only fix I know is to just re-run the build & 🤞

**Comment by thoutenbos** [comment]
@jeffbyrnes yeah I noticed that, but it seems to be consistent unfortunately. Working to see if I can get it fixed as I really like to have the build working.

**Comment by jeffbyrnes** [comment]
@thoutenbos agreed. Let me know if I can help; maybe something else needs a kick, or maybe we need to use a newer Docker image.

**Comment by thoutenbos** [comment]
@jeffbyrnes I've been looking at it all night but cannot seem to get anywhere yet. Disabling the SSL verification is also fine for me (for the test kitchen) but cannot seem to get that option passed in either. Would be great if you can give it a try, maybe you are able to get anywhere :)

Getting the build to pass is the last thing on my list before packaging a new release.

**Comment by jeffbyrnes** [comment]
I’ll try to take a peek tomorrow. Lots of work work to do, so it might slip, but I’ll try my best.

**Comment by jeffbyrnes** [comment]
Circling back to this, let’s see what we can see…

**Pull request merged**
