### PR TITLE
Do not allow a crt without an accompanying chain

### LINKED ISSUE #44: Disallow defining `crt` without `chain`
I got bit by this when I was generating certificates without any chains. Oddly, they worked in some browsers but not others, so it went unnoticed for a bit. I definitely intended to use `fullchain`, but instead had a bunch of certificates with no root attached with no way to even fix without re-issuing new certificates.

I likely would have caught this if the provider yelled at me for declaring `crt` without a `chain`. It seems hazardous to allow one without the other unless I'm missing any scenario where that'd be acceptable.

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes #44

### CODE REVIEW

**Comment by thoutenbos** [comment]
What if the `fullchain` attribute is used? The chain will be written to the cert/chain combined file but the cookbook will now fail since `chain` is required.

**Comment by mattrobenolt** [comment]
I'd be ok with allowing that. It needs either `fullchain` or `chain`. I can update PR.

**Comment by thoutenbos** [comment]
@mattrobenolt could you please update the PR ?

**Comment by thoutenbos** [comment]
Rebased, edited and merged
https://github.com/schubergphilis/chef-acme/commit/f9e96e138a84c705916849cdb4e0836248473cbf

**Pull request closed without merging**
