### PR TITLE
add support for tls_sni01

### PR DESCRIPTION
**Pull request by axos88**
- add new resource for tls verification with pluggable server setup (implemented for nginx for reference)
- fixed kitchen tests #53 
- minor cleanups
- add alt_names for the ssl_selfsigned resource

### CODE REVIEW

**Comment by axos88** [comment]
retest this please

**Comment by axos88** [comment]
not sure what's happening there, the error is invalid.

**Comment by axos88** [comment]
@schuberphilis, could you take a look?

**Comment by axos88** [comment]
@thoutenbos any chance you could review this please?

**Comment by thoutenbos** [comment]
Hi @axos88,

Thanks for your contribution!

This seems to be a really big change, combining several functional changes in one PR. Next to that the build is currently failing. I'll have to fix the build, then review this carefully for any breaking changes before merging.

Cheers,
Thijs

**Comment by axos88** [comment]
@thoutenbos yeah... sorry about that. Let me know when you have the build fixed.

**Comment by thoutenbos** [comment]
@axos88 sorry for the delay, build is fixed now in travis and Kitchen (for CentOS 7).

While reviewing your changes I noticed you've created a new provider instead of extending on the exiting one. That means there will be two providers, one for http and another for ssl validation. Originally I had envisioned the `method` property on the provider to be used for this switch. Any chance to implement the ssl validation as `ssl` method on the original provider?

**Comment by axos88** [comment]
If you take a closer look, you will find that the way the provider I wrote works is totally different, due to the fact that the TLS check needs much more complicated ways to set up the verification, which is unnecessary for the HTTP checks

I don't think these should go into the same resource, as some attributes do not make sense for the HTTP, and others for the TLS check (webroot, and webserver respectively).

I did implement the new provider in a way that it's extensible for multiple webservers for setting up and tearing down the checks.

**Comment by thoutenbos** [comment]
Okay, sounds good. Currently the integration tests and validation recipes are not running in travis, probably because of your rename. If you could fix that then I should be able to merge it in.

**Comment by thoutenbos** [comment]
Would also be nice if you could add some information to the README on how to use the new SSL provider.

**Comment by axos88** [comment]
Will do, I'm currently on vacation, so around next week.

**Comment by thoutenbos** [comment]
@axos88 hope you had a great holiday :)

Would you be able to rebase and update the README ?

**Comment by axos88** [comment]
ha. will do.

**Comment by axos88** [comment]
See #75

**Pull request closed without merging**
