### PR TITLE
Release version 3.2.0

### PR DESCRIPTION
**Pull request by ibaum**
We're looking to include this with changes from https://github.com/schubergphilis/chef-acme/pull/86 in GitLab 10.5. 

It would be great to have a released version with these changes.

### CODE REVIEW

**Comment by thoutenbos** [comment]
I’ll be able to upload a new release to the Chef supermarket in two weeks from now, also intend to include the outstanding changes from @jeffbyrnes in that.

Is that in time for your release?

**Comment by ibaum** [comment]
It won't be, but it isn't a big deal. We can build against a commit hash for now, and update to the release tag when that is out.

**Comment by oliver-whiteman** [comment]
Any update on this release being prepped?
Thanks

**Comment by thoutenbos** [comment]
Version 4.0.0 released

**Pull request closed without merging**
