### PR TITLE
Update certificate when common name / alternate names change

### LINKED ISSUE #35: Certificate is not updated when common name / alternate names changed
The letsencrypt provider only creates a new certificate if the certificate file does not exist or if the certificate is approaching expiry. If there is a valid non-expired certificate on disk at the specified path then the provider does nothing.

I think it should also check that the common name and alternate names on the existing certificate match those declared on the resource, and provision a new certificate if any of those have changed?

### PR DESCRIPTION
**Pull request by wndhydrnt**
This change makes it possible to update the certificate when the
common name changes or alternate names are added or removed.

Fixes #35

### CODE REVIEW

**Comment by wndhydrnt** [comment]
I'd like to add a test for this but I'm not sure how. My approach would be to use an existing certificate that has the SANs `test.example.com` and `web.example.com` in it, but is missing `mail.example.com`. 
The cookbook in `test/fixtures/` would then try to create a certificate that includes all three names.
Does that sound right to you?

**Comment by thoutenbos** [comment]
Test case sounds good to me!

**Comment by thoutenbos** [comment]
@wndhydrnt could you take a look at that test case? I want to release a new version and would like this feature to be included.

**Comment by wndhydrnt** [comment]
@thoutenbos Thanks for the reminder! I've added a test case and it passes on Travis. I'm not sure about the location of the specs though. Can they stay in the http suite or is it better to create a new suite to express that it's a special test case?

**Comment by thoutenbos** [comment]
Thanks! Location should be fine.

**Pull request merged**
