### PR TITLE
Chef 13 support

### PR DESCRIPTION
**Pull request by rnt**
Enable acme cookbook to use in Chef 13.

Tested with `kitchen test centos-7` and running successfully.
:)

### CODE REVIEW

**Comment by thoutenbos** [comment]
Build is failing. Pinning rabbitmq to version `3.6.1` will probably fix it. The chef run in travis is a bit picky about the new version for some reason.

**Comment by rmoriz** [comment]
What exactly does this fix? Chef13 already worked in master?

**Comment by rnt** [comment]
@thoutenbos travis failed because the execution was 10 minutes without text output. When I did the test (kitchen-vagrant-virtualbox) it took about 15 minutes in total, but that did not happen.

@rmoriz this PR fixed the tests running with kitchen (and bump version).

**Comment by rmoriz** [comment]
`mariadb` seems to be broken on CentOS. I'm getting the following error:
https://travis-ci.org/rmoriz/chef-acme#L2098

**Comment by rmoriz** [comment]
The RabbitMQ startup timeout also happens in the CI of the rabbitmq cookbook… 

see https://github.com/rabbitmq/chef-cookbook/issues/435

**Comment by thoutenbos** [comment]
@rnt does it still make sense to rebase this after #71 ?

**Comment by thoutenbos** [comment]
Should be obsolete by now

**Pull request closed without merging**
