### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by zakame**
- Fix nginx setup in acme_client test cookbook (was looking to upgrade nginx cookbook dependency to v10 but there's a lot of breaking changes there, so work around for now.)
- Use Pebble v1.0.1 instead of master/v2.x (in a similar situation to the nginx cookbook above.)

### CODE REVIEW

**Comment by thoutenbos** [comment]
Cool stuff!

**Comment by zakame** [comment]
Thanks! Forgot one more commit though, I'll just make another PR

**Comment by zakame** [comment]
Ah just saw https://github.com/schubergphilis/chef-acme/commit/38e72bc228323e59dbdfafc8a5a0736630d88933 :+1:

**Comment by thoutenbos** [comment]
Very happy to have the Travis working again! :-)

**Pull request merged**
