### PR TITLE
Add note in README

### PR DESCRIPTION
**Pull request by rnt**
Add note to README.md related to changes from 2.0.0 to 3.0.0

### CODE REVIEW

**Comment by thoutenbos** [comment]
`validation_method` property was removed in https://github.com/schubergphilis/chef-acme/commit/a0892f1e9317128f9d2af1e1f6b91fbeef3c53ff

**Comment by rnt** [comment]
@thoutenbos right! I think the README.md need a messages to say that.

**Comment by thoutenbos** [comment]
Well I did put it in the CHANGELOG, but feel free to add it to README as well if you feel it is needed

**Comment by rnt** [comment]
@thoutenbos good, I miss that change. I'm close the PR.

**Pull request closed without merging**
